export const videosData = {
  "1-3": [
    {
      id: 1.1,
      title: "Grade 1-3 Video 1",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.youtube.com/watch?v=0hq3DrAJY_c",
    },
    {
      id: 1.2,
      title: "Grade 1-3 Video 2",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.youtube.com/watch?v=tflQ33g6I8I",
    },
    {
      id: 1.3,
      title: "Grade 1-3 Video 3",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 1.4,
      title: "Grade 1-3 Video 4",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 1.5,
      title: "Grade 1-3 Video 5",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 1.6,
      title: "Grade 1-3 Video 6",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 1.7,
      title: "Grade 1-3 Video 7",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 1.8,
      title: "Grade 1-3 Video 8",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
  ],
  "4-6": [
    {
      id: 2.1,
      title: "Grade 4-6 Video 1",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 2.2,
      title: "Grade 4-6 Video 2",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 2.3,
      title: "Grade 4-6 Video 3",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 2.4,
      title: "Grade 4-6 Video 4",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 2.5,
      title: "Grade 4-6 Video 5",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 2.6,
      title: "Grade 4-6 Video 6",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 2.7,
      title: "Grade 4-6 Video 7",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 2.8,
      title: "Grade 4-6 Video 8",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
  ],
  "7-8": [
    {
      id: 3.1,
      title: "Grade 7-8 Video 1",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 3.2,
      title: "Grade 7-8 Video 2",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 3.3,
      title: "Grade 7-8 Video 3",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 3.4,
      title: "Grade 7-8 Video 4",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 3.5,
      title: "Grade 7-8 Video 5",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 3.6,
      title: "Grade 7-8 Video 6",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 3.7,
      title: "Grade 7-8 Video 7",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 3.8,
      title: "Grade 7-8 Video 8",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
  ],
  "9-10": [
    {
      id: 4.1,
      title: "Grade 9-10 Video 1",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 4.2,
      title: "Grade 9-10 Video 2",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 4.3,
      title: "Grade 9-10 Video 3",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 4.4,
      title: "Grade 9-10 Video 4",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 4.5,
      title: "Grade 9-10 Video 5",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 4.6,
      title: "Grade 9-10 Video 6",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 4.7,
      title: "Grade 9-10 Video 7",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 4.8,
      title: "Grade 9-10 Video 8",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
  ],
  "11-12": [
    {
      id: 5.1,
      title: "Grade 11-12 Video 1",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 5.2,
      title: "Grade 11-12 Video 2",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 5.3,
      title: "Grade 11-12 Video 3",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 5.4,
      title: "Grade 11-12 Video 4",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 5.5,
      title: "Grade 11-12 Video 5",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 5.6,
      title: "Grade 11-12 Video 6",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
    {
      id: 5.7,
      title: "Grade 11-12 Video 7",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/movie.mp4",
    },
    {
      id: 5.8,
      title: "Grade 11-12 Video 8",
      thumbnail: "https://via.placeholder.com/150",
      videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    },
  ],
};
